//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Menus = new HashSet<Menu>();
            this.ServiceDetails = new HashSet<ServiceDetail>();
        }
    
        public int BookingId { get; set; }
        public string GroomName { get; set; }
        public string BrideName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> HallId { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> TableCount { get; set; }
        public Nullable<int> ReserveTableCount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TablePrice { get; set; }
        public Nullable<decimal> TotalTableAmount { get; set; }
        public Nullable<decimal> TotalServiceAmount { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
    }
}
