//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA()
        {
            this.PHIEUDATTIECs = new HashSet<PHIEUDATTIEC>();
        }
    
        public int MaCa { get; set; }
        public string TenCa { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBatDauCa { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKetThucCa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATTIEC> PHIEUDATTIECs { get; set; }
    }
}
