//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDV
    {
        public string MaPhieuDat { get; set; }
        public string MaDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUDATTIEC PHIEUDATTIEC { get; set; }
    }
}
