//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBAOCAOD
    {
        public int Ngay { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<int> SoLuongTiec { get; set; }
        public Nullable<decimal> DoanhThu { get; set; }
        public Nullable<decimal> TiLe { get; set; }
    
        public virtual BAOCAOD BAOCAOD { get; set; }
    }
}
