//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTiecCuoiEntities : DbContext
    {
        public QuanLyTiecCuoiEntities()
            : base("name=QuanLyTiecCuoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAOD> BAOCAODS { get; set; }
        public virtual DbSet<CA> CAs { get; set; }
        public virtual DbSet<CHITIETDV> CHITIETDVs { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<CTBAOCAOD> CTBAOCAODS { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<LOAISANH> LOAISANHs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NHOMNGUOIDUNG> NHOMNGUOIDUNGs { get; set; }
        public virtual DbSet<PHIEUDATTIEC> PHIEUDATTIECs { get; set; }
        public virtual DbSet<SANH> SANHs { get; set; }
        public virtual DbSet<THUCDON> THUCDONs { get; set; }
    }
}
