//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATTIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATTIEC()
        {
            this.CHITIETDVs = new HashSet<CHITIETDV>();
            this.THUCDONs = new HashSet<THUCDON>();
        }
    
        public int MaPhieuDat { get; set; }
        public string TenChuRe { get; set; }
        public string TenCoDau { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayDatTiec { get; set; }
        public Nullable<System.DateTime> NgayDaiTiec { get; set; }
        public Nullable<int> MaCa { get; set; }
        public Nullable<int> MaSanh { get; set; }
        public Nullable<decimal> TienDatCoc { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> SoBanDuTru { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> DonGiaBanTiec { get; set; }
        public Nullable<decimal> TongTienBan { get; set; }
        public Nullable<decimal> TongTienDV { get; set; }
        public Nullable<decimal> TongTienHoaDon { get; set; }
        public Nullable<decimal> TienConLai { get; set; }
        public Nullable<decimal> ChiPhiPhatSinh { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
    
        public virtual CA CA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDV> CHITIETDVs { get; set; }
        public virtual SANH SANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCDON> THUCDONs { get; set; }
    }
}
