//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueReportDetail
    {
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> WeddingCount { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Ratio { get; set; }
    
        public virtual RevenueReport RevenueReport { get; set; }
    }
}
