//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCDON
    {
        public int MaPhieuDat { get; set; }
        public int MaMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int ThuTuLenMon { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MONAN MONAN { get; set; }
        public virtual PHIEUDATTIEC PHIEUDATTIEC { get; set; }
    }
}
